# Generated by Django 2.2.28 on 2024-01-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20240119_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choicetext',
            new_name='choice_text',
        ),
    ]
